repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: local
    hooks:
      - id: check-python-version
        name: Check Python Version
        entry: python -c "import sys; exit(0) if sys.version_info[:2] == (3, 11) else exit(1)"
        language: system
        pass_filenames: false
      - id: run-tests
        name: Run Tests
        entry: pytest
        language: system
        pass_filenames: false