version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: quickbook_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quickbook_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qb_network

  api:
    build: .
    image: "qb_api"
    container_name: fastapi_container
    entrypoint: ["/app/scripts/docker_entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      - db
    networks:
      - qb_network
    env_file:
      - .env

  cache:
    image: redis:6.2.6-bullseye
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - qb_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - qb_network

volumes:
  postgres_data:
  postgres_data_test:
  redis:

networks:
  qb_network:
    driver: bridge
