version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: quickbook_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quickbook_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - my_network


  api:
    build: .
    image: "qb_api"
    container_name: fastapi_container
    entrypoint: ["/app/scripts/docker_entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      - db
    networks:
      - my_network
    env_file:
      - .env





volumes:
  postgres_data:
  postgres_data_test:

networks:
  my_network:
    driver: bridge

